eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8765/eureka/
server:
  port: 3031
spring:
  application:
    name: userms
  h2:
    console:
      enable: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411
